### ISSUE TITLE
Do not use or suggest using setx command on Windows

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bvm#11]
Hello! You should never suggest the user to use `setx` command on Windows like in this warning:

```
global Bit install location was not found in your PATH global variable.
please run the following command and then re-open the terminal:
setx path "%path%;C:\Users\Komputer\AppData\Local\.bvm" and re-open your terminal
for more information read here - https://harmony-docs.bit.dev/introduction/installation
```

`setx` is potentially dangerous because it has 1024 character limit. If you exceed this limit, then the PATH variable will be truncated to 1024 chars which will break the user's machine.
You can read more about this issue here:
https://superuser.com/questions/812754/how-to-recover-from-path-being-truncated-to-1024-characters-by-setx
https://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx
https://stackoverflow.com/a/37304698

**Comment by Alphavader** [comment]
The setx command does not work for me either.. what can we do to link "bvm" and make it work ?
