### ISSUE TITLE
bvm install - affected by colors.js 

### ISSUE THREAD

**Issue by BenTomsett** [teambit/bvm#25]
Running `bvm install` on the latest version on npm (`0.0.30`) produces garbage output

![](https://user-images.githubusercontent.com/25419125/148666190-436b0248-80a2-4f85-aaf4-83a0d2d6469d.png)

related to this commit in colors.js - Marak/colors.js@074a0f8ed0c31c35d13d28632bd8a049ff136fb6

**Comment by itaymendel** [comment]
hi, thanks for the heads up.
looking into it right now.

**Comment by guysaar223** [comment]
fixed

**Comment by GiladShoham** [comment]
fixed on version 0.0.31 of bvm
