### ISSUE TITLE
Older versions not available

### ISSUE THREAD

**Issue by yayudev** [teambit/bvm#28]
Seems like only the latest 20 versions are available to install. This is currently breaking our CI since we can't upgrade to `> 0.0.653` due to compile errors and the one we had it fixed to (`0.0.651`) is no longer available to install.

You can replicate it even if you run `bvm list --remote`, you'll only get the latest 20. I think this intended since you can use `--limit=XXX` to see older versions but seems like the default limit of 20 is also limiting the list of versions available to install to only the latest 20.

Did a quick research and the problem seems to be that `slice` method's `limit` arg has a default value of `20`
https://github.com/teambit/bvm/blob/main/teambit.bvm/list/version-list/remote-version-list.ts#L15

but the limit is never changed when fetching, so only fetches the latest 20 versions
https://github.com/teambit/bvm/blob/main/teambit.bvm/fetch/fetch.ts#L32

So maybe removing the limit/slicing and passing the 20 default limit when running `list` could be a better approach

I could create a PR for this but I'm not sure how to test bvm locally. If you could guide me or point me to any guide on how to do it I can do it myself, otherwise let me know if you guys need any extra info from me.

**Comment by GiladShoham** [comment]
fixed on version 0.0.35 by https://github.com/teambit/bvm/pull/35
