### ISSUE TITLE
'bvm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by miliko0022** [teambit/bvm#39]
I have installed `npx @teambit/bvm install`.  After that I want to check bvm and bit. bit working, and bvm throws an error 

>bvm : The term 'bvm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
> bvm -v 

![image](https://user-images.githubusercontent.com/32756313/161401482-e3cb6245-aa28-46d7-ae48-7fc40c4e166e.png)

**Comment by GiladShoham** [comment]
if you use npx, it won't add it to your global bin folder (by design)
if you want to have bvm command, you need to install it globally `npm install -g @teambit/bvm`
