### ISSUE TITLE
new feature "install node.js" breaks bvm on systems not using glibc

### ISSUE THREAD

**Issue by tw-hotelplan** [teambit/bvm#46]
`/root/bin/bit: line 9: /root/.bvm/nodejs/16.15.1/bin/node: not found`

A very popular distribution which is used to build (docker) images is Alpine. Alpine uses musl instead of glibc. The nodejs binary which is downloaded by bvm is linked to glibc and does not run/work on Alpine leading to the above error message.

Is it possible to make the download optional? Or check current node version and only install if different?

I've seen `/root/bin/bit`:

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

export PATH="/root/.bvm/nodejs/16.15.1/bin:$PATH"
"/root/.bvm/nodejs/16.15.1/bin/node"  "$basedir/../.bvm/versions/0.0.775/bit-0.0.775/node_modules/@teambit/bit/bin/bit" "$@"
exit $?
```

By adding `/root/.bvm/nodejs/16.15.1/bin` to the front of the PATH, shell will try `/root/.bvm/nodejs/16.15.1/bin/node` first, so an absolute path is not necessary for the command itself. Just `node` would take the first "working" binary/executable in the PATH, using the 16.15.1 version for most of the users and "fallback" to the standard/installed versions for the rest of us.

**Comment by GiladShoham** [comment]
Thanks for reporting, we will make it optional, and also check if we can fix it for alpine regardless

**Comment by zkochan** [comment]
We can add an option to skip Node.js installation. And additionally we can automatically skip Node.js installation, when the libc is musl.

**Comment by tw-hotelplan** [comment]
Thank you.

```
SHELL=/bin/bash bvm upgrade --use-system-node
```

Works. 👏
