### ISSUE TITLE
$bvm install stuck at "downloading version..."

### ISSUE THREAD

**Issue by kduy969** [teambit/bvm#60]
I'm trying to install bit on my pc but the installation is stuck forever at downloading step after 1-2 mins of installation, tried multiple times with other node versions, turning off Windows Firewall, and Windows Security, but still gives the same result.
Steps to reproduce: 

1. $npm install -g teambit/bvn
1. $bit install
![image](https://user-images.githubusercontent.com/5911229/185045382-0b3c95c1-20ed-4f26-9dcb-bd44fc3a7bc2.png)
OS: Windows 11
Node: v16.16.0

**Comment by GiladShoham** [comment]
please run bvm list -r 
then try to manually download the file and see if it works for you
