### ISSUE TITLE
bvm installation problem on window

### ISSUE THREAD

**Issue by csckhw303** [teambit/bvm#66]
I've tried many possible installation as below:
  npm i -g teambit/bvm
  npx teambit/bvm install

Check path on my env. variable. it has "C:/Users......./.bvm"
I close and open the terminal again to run bvm install. But it complains "bvm is not recognized as an internal or external command,
operable program or batch file."

Only thing is I open the ./bvm folder, I do not see any bvm file at all. Only bit and bit.cmd with 3 folders.

What do you think I missed?

**Comment by arthus111** [comment]
@csckhw303 , You omitted '@'symbol. You should type "npm i -g @teambit/bvm"

**Comment by GiladShoham** [comment]
please read here - https://bit.dev/reference/reference/using-bvm#bvm-is-not-recognized-in-your-terminal
this is not really bit related issue, but general issue with npm and windows.
